### ISSUE TITLE
Need a helper to populate all mentioned github labels 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/release-action#12]
So similar one to `auto`, but now operating on the configs found in the repo and populating also CHANGELOG-missing

**Comment by jwodder** [comment]
@yarikoptic Should this support setting the label descriptions and/or colors via the config file, like auto does?

**Comment by yarikoptic** [comment]
> @yarikoptic Should this support setting the label descriptions and/or colors via the config file, like auto does?

Please!  That would be very nice to have.  I do not really care about which colors (probably the same as `auto` since some might have used to them) but would appreciate consistency

> Also, nothing in the code is tied to `CHANGELOG-missing`, so should that label only be created if some additional option or config is given?

oh, because it is templated into the action to ship?  (greedy me now wants https://github.com/datalad/release-action/issues/14 ;)) The lazy me would have liked it to be auto-determined (e.g. via `grep rm-labels .github/workflows/*` or alike) but if you feel that would be too fragile, I guess has to be specified indeed :-/
