### ISSUE TITLE
"Update Major Version Tag" workflow not triggered by "release" workflow

### ISSUE THREAD

**Issue by jwodder** [datalad/release-action#21]
The "Update Major Version Tag" workflow is triggered by pushing a new tag with a name of the form `v*`, but since the release workflow is the one that does this — i.e., the tag is pushed using a GitHub Actions `GITHUB_TOKEN` — GitHub Actions refuses to trigger the tag workflow due to its policy of not triggering workflows on activity performed by other workflows so as not to create an infinite loop.

Possible solutions:

- Look for a different action for updating version tags that can be run within the "release" workflow rather than requiring a separate, tag-triggered workflow
- Implement tag-updating ourselves as another `datalad_release_action` command
- Use a different, dedicated API token for checking out & pushing to this repository in the "release" workflow

**Comment by jwodder** [comment]
@yarikoptic There's no need for a `post-release-cmd` option; if you want to do something after a release, add more steps after the release action in the workflow.

**Comment by yarikoptic** [comment]
Indeed, unless you want to concentrate all such specifics on the config file so you could trigger those steps locally, not from workflow. But ok for now just do in workflow since singular use case etc
