### ISSUE TITLE
Make workflow exit clean green (not skipped grey) if PR has a changelog snippet addded 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/release-action#28]
Looking at current https://github.com/datalad/datalad/pull/7107 we have `1 skipped and 21 successful checks` and overall the list of checks expanded since not all green.  In a typical PR we should expect for changelog snippet to be added. So I would prefer if workflow helped to visualize that
- be grey if no changelog pr-XXX.md was added (produced by this workflow or not)
- be green if there was a changelog .md added (produced by the workflow upon adding CHANGELOG-missing or not, shouldn't matter)

WDYT - would it be possible to do?

**Comment by jwodder** [comment]
@yarikoptic That would only be possible if the "Add changelog.d snippet" workflow always ran rather than only running when the `CHANGELOG-missing` label is present, which is the opposite of what you said to do in #9.

**Comment by yarikoptic** [comment]
> @yarikoptic That would only be possible if the "Add changelog.d snippet" workflow always ran rather than only running when the `CHANGELOG-missing` label is present,

but if it always runs, can it also be "skipped" some times then ( I guess if previous step sets some variable and the next one skips in `if`?)?

> which is the opposite of what you said to do in https://github.com/datalad/release-action/issues/9.

well, we are still yet to establish the ultimately "convenient" workflow so my visionary nature sometimes is not perfect and I might come up with improvements which are not matching earlier ideas ;)

**Comment by yarikoptic** [comment]
eh, ok, let's keep as is for now then
