### ISSUE TITLE
An alternative way (to PR) to trigger cutting a release

### ISSUE THREAD

**Issue by yarikoptic** [datalad/release-action#34]
ATM requires a PR, PR requires a commit, that requires annotations to make CIs to skip it to avoid CIs uselessly waste CPU cycles, ...

I wonder what other way we could instrument typically or what other projects do?  I think it could be

- :heart: make `release` workflow react on having a new issue created with a label `release` (IIRC only developers can add labels) and then close that issue upon release
- :rocket: `workflow_dispatch` which would result in "Run workflow" button on the release action page.
- ... suggest anything better? ...

@jwodder WDYT?

**Comment by jwodder** [comment]
@yarikoptic One option would be to have the `release` workflow able to be triggered manually via `workflow_dispatch` (like the "Run workflow" button on https://github.com/datalad/git-annex/actions/workflows/build-ubuntu.yaml).  I think that only users with write permission to the repository would be able to use this.

**Comment by yarikoptic** [comment]
That's a nice idea too!  `release` issue I would like a little more because it would provide some kind of easier accessible provenance on who has triggered the release, but action does have that annotation as well

![image](https://user-images.githubusercontent.com/39889/199757306-13183b37-e61e-4844-8808-75b6a4142cab.png)

I guess it should be easier to implement than the "issue" approach, right?

Just a few points relevant to both of issue and "workflow_dispatch"
- we shouldn't forget to document it in https://github.com/datalad/datalad/blob/HEAD/CONTRIBUTING.md#releasing-with-github-actions-auto-and-pull-requests (which needs to be adjusted already anyways)
- most likely it should gain preventive mechanism to not re-release if current `git describe` already corresponds to a release tag
