### ISSUE TITLE
Release it

### ISSUE THREAD

**Issue by yarikoptic** [datalad/release-action#49]
We are at v1.0.1-33-g111cdf5 and it seems to be used quite stably -- let's release.

**Comment by jwodder** [comment]
@yarikoptic A PR is required in order to make a release.

**Comment by yarikoptic** [comment]
please send a PR then

**Comment by jwodder** [comment]
@yarikoptic To do what?

**Comment by yarikoptic** [comment]
to create a new release of the release-action: we have gone without any release for a while and accumulated a notable amount of changes according to git describe in the original post.

**Comment by jwodder** [comment]
@yarikoptic I meant, what should the PR do/contain?

**Comment by yarikoptic** [comment]
Whatever is necessary to get release out. Could be empty for what I care
