### ISSUE TITLE
Update `version` field within CITATION.cff upon release 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/release-action#52]
ATM in datalad we have aged entry

```shell
❯ pwd
/home/yoh/proj/datalad/datalad-maint
❯ git describe
0.19.5-6-gb254e0ff7
❯ grep '^version' CITATION.cff
version: 0.14.6
```

which should be updated along with each release

**Comment by jwodder** [comment]
@yarikoptic This can & should be done via [the `pre-tag` script provided to the "release" action](https://github.com/datalad/datalad/blob/b254e0ff7c8896a9f0bb91bc314a3b6a8aae71de/.github/workflows/release.yml#L40), e.g.:

```
pre-tag:
    # Insert current script contents here
    perl -pli -e "s/^version: .*/version: $new_version/" CITATION.cff
    git commit -m '[skip ci] Update CITATION.cff' CITATION.cff
```

**Comment by yarikoptic** [comment]
ok, for now we could do it this way -- makes sense.  It is just because it should be a very common case that if there is CITATION.cff - version need to be boosted -- I thought it would make sense to make it "automated". We can leave with custom action for now. Thanks!
