### ISSUE TITLE
"Action" on added in a PR changelog snippet

### ISSUE THREAD

**Issue by yarikoptic** [datalad/release-action#9]
Moving discussion from https://github.com/datalad/datalad/pull/7081#issuecomment-1279000592

> @yarikoptic Could you specify what you want the action to do with and without `CHANGELOG-missing` (or other configured label) in the following cases:
> 
> * There are no changelog snippets in the PR

what does now -- `scriv create` the `pr-PRNUM.md`

> * There is one changelog snippet in the PR, and its name is not in `pr-PRNUM.md` format

`git mv SNIPPET.md pr-PRNUM.md`

> * There are multiple changelog snippets in the PR

if they are already `pr-PRNUM.md` format - nothing to do.  Otherwise - more than one not in pr-PRNUM.md, error out since ATM we can't/don't want to do anything. User can join manually. If we get to use case where we would care - we  tune it up

**Comment by jwodder** [comment]
@yarikoptic 

> if they are already `pr-PRNUM.md` format - nothing to do

Do you mean if they're *all* in that format?

> Otherwise - more than one not in pr-PRNUM.md, error out

What if there's one in `pr-PRNUM.md` format and one not in that format?

**Comment by bpoldrack** [comment]
I think it should only be concerned with a matching `PRNUM`. If that exists - nothing to do. If multiple matches - error our with a message stating that those should likely be joined (or somehow fixed for misnaming).

**Comment by yarikoptic** [comment]
> > if they are already `pr-PRNUM.md` format - nothing to do
> 
> Do you mean if they're _all_ in that format?

just 1 in that diff. If there is none in that diff -- generate one from the title.

**Comment by yarikoptic** [comment]
> > Otherwise - more than one not in pr-PRNUM.md, error out
> 
> What if there's one in `pr-PRNUM.md` format and one not in that format?

agree with @bpoldrack - again based only on the diff, not all present -- error out and suggest to join into a single one. no point to proliferate.  If any custom list of snippets to be added, ppl can do - just would not trigger action via label ;-)

**Comment by jwodder** [comment]
@yarikoptic To be clear, if a PR adds multiple scriv fragments, then:

* If one of them is of the form `pr-PRNUM.md` where `PRNUM` is the number of the pull request, do nothing
* Otherwise, error out.

Is that what the action should do?

Also, you haven't addressed [this comment](https://github.com/datalad/release-action/issues/9#issuecomment-1279030251) yet.

**Comment by yarikoptic** [comment]
> Is that what the action should do?

I think so

> Also, you haven't addressed [this comment](https://github.com/datalad/release-action/issues/9#issuecomment-1279030251) yet.
> @yarikoptic So the `CHANGELOG-missing` label shouldn't have any effect on what the action does? Should the suggested workflow still be triggered by the presence of the label, or should it "always" run?

my thinking so far -- only by the presence of the label (as also hinted in the [comment above](https://github.com/datalad/release-action/issues/9#issuecomment-1279347980) as to still be able to do "custom/multiple scriv fragments".
